# Generated by Django 5.0.4 on 2024-05-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_management_system', '0009_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
