# Generated by Django 5.0.4 on 2024-06-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_management_system', '0014_customuser_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='remaining_leave',
        ),
    ]
