from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views
from .views import *
from django.contrib.auth import views as auth_views


# Define your viewsets
router = DefaultRouter()
router.register(r'salary_slips', SalarySlipViewSet)
router.register(r'notifications', NotificationViewSet)
router.register(r'leave-requests', LeaveRequestViewSet, basename='leave-requests')
router.register(r'admin-leave-requests', AdminLeaveRequestViewSet, basename='admin-leave-requests')

# Add your custom URL patterns
urlpatterns = [
    # URL patterns generated by router
    *router.urls,
    path('contact/', ContactView.as_view(), name='contact_us'),
    path('login/', UserLoginAPIView.as_view(), name='user_login'),
    path('register/', UserRegisterAPIView.as_view(), name='user_register'),
    path('logout/', UserLogoutAPIView.as_view(), name='user_logout'),
    path('users/', CustomUserListCreateAPIView.as_view(), name='user-list-create'),
    path('users/<int:pk>/', CustomUserRetrieveUpdateDestroyAPIView.as_view(),
         name='user-detail'),
    path('user/search/', search_users, name='search_user_api'),

    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
